name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - release_web

# 添加权限配置
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 可根据项目需求调整 Node.js 版本

      - name: Install dependencies
        run: |
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set fetch-retries 5
          npm install   --registry=https://registry.npmjs.org
        working-directory: frontend
        
      - name: Setup environment variables
        run: |
          # 创建或修改 .env 文件，设置生产环境的 API URL
          echo "VITE_APP_BASE_URL=${{ secrets.API_BASE_URL || 'http://127.0.0.1/v1/api' }}" > .env
          # 仍然设置基础路径
          echo "VITE_BASE_URL=/KnowledgeQuery/" >> .env
          cat .env
        working-directory: frontend

      - name: Build project
        run: |
          npm run build
        working-directory: frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist